version: "3.3"

services:
  mariadb:
    build: 
      context: ./requirements/mariadb/
      args:
        MYSQL_DATABASE=${MYSQL_DATABASE}
        MYSQL_USER=${MYSQL_USER}
        MYSQL_PASSWORD=${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
    container_name: mariadb
    volumes:
      -  mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - wordpress 
    restart: always
    init : true
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - wordpress
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    init : true
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    networks:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    init : true

networks:
  wordpress:
    driver: bridge

volumes :
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/atarchou/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/atarchou/data/mariadb
      o: bind
